u21447234_HW3/u21447234_HW3/Models/FileModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace u21447234_HW3.Models
{
    public class FileModel
    {
        [Display(Name = "File Name")]
        public string FileName { get; set; }
        public HttpPostedFileBase[] Files { get; set; }
    }
}

u21447234_HW3/u21447234_HW3/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using u21447234_HW3.Models;


namespace u21447234_HW3.Controllers
{
    public class FileController : Controller
    {
        public ActionResult Index()
        {
            string[] filePaths = Directory.GetFiles(Server.MapPath("~/App_Data/document/"));

            List<FileModel> files = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath) });
            }
            return View(files);
        }

        public FileResult DownloadFile(string fileName)
        {
            string path = Server.MapPath("~/App_Data/document/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {
            string path = Server.MapPath("~/App_Data/document/") + fileName;

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }
}

u21447234_HW3/u21447234_HW3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace u21447234_HW3.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase files, string rbSelection)
        {
            if (files != null && files.ContentLength > 0)
            {
                var fileName = Path.GetFileName(files.FileName);
                var path = "";

                if (rbSelection == "Doc")
                {
                    path = Path.Combine(Server.MapPath("~/App_Data/document"), fileName);
                }
                else if(rbSelection == "Img")
                {
                    path = Path.Combine(Server.MapPath("~/App_Data/image"), fileName);
                }
                else if(rbSelection == "Vid")
                {
                    path = Path.Combine(Server.MapPath("~/App_Data/video"), fileName);
                }
                files.SaveAs(path);
            }
            return RedirectToAction("Index");
        }

        public ActionResult AboutMe()
        {
            return View();
        }
    }
}

u21447234_HW3/u21447234_HW3/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using u21447234_HW3.Models;

namespace u21447234_HW3.Controllers
{
    public class ImageController : Controller
    {
        // GET: Image
        public ActionResult Index()
        {
            string[] imagePaths = Directory.GetFiles(Server.MapPath("~/App_Data/image/"));

            List<FileModel> images = new List<FileModel>();

            foreach (string imagePath in imagePaths)
            {
                images.Add(new FileModel { FileName = Path.GetFileName(imagePath) });
            }
            return View(images);
        }

        public FileResult DownloadImage(string fileName)
        {
            string path = Server.MapPath("~/App_Data/image/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteImage(string fileName)
        {
            string path = Server.MapPath("~/App_Data/image/") + fileName;

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }
}

u21447234_HW3/u21447234_HW3/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using u21447234_HW3.Models;

namespace u21447234_HW3.Controllers
{
    public class VideoController : Controller
    {
        public ActionResult Index()
        {
            string[] videoPaths = Directory.GetFiles(Server.MapPath("~/App_Data/video/"));

            List<FileModel> videos = new List<FileModel>();

            foreach (string videoPath in videoPaths)
            {
                videos.Add(new FileModel { FileName = Path.GetFileName(videoPath) });
            }
            return View(videos);
        }

        public FileResult DownloadVideo(string fileName)
        {
            string path = Server.MapPath("~/App_Data/video/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteVideo(string fileName)
        {
            string path = Server.MapPath("~/App_Data/video/") + fileName;

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }
}

u21447234_HW3/u21447234_HW3/Views/File/Index.cshtml
@using u21447234_HW3.Models
@model List<FileModel>

@{
    ViewBag.Title = "Files";
    ViewBag.Message = "All your uploaded files will appear here.";
}

<h2><b>@ViewBag.Title</b></h2>
<h4>@ViewBag.Message</h4>

<style>
    .middle {
        text-align: center;
    }

    body {
        background-image: radial-gradient(circle, blue, aqua, lightskyblue, lightblue);
        background-attachment: fixed;
    }

    .table {
        margin-top: -20px;
    }
</style>

<div class="well-lg" style="background-color: #262626;">
    <table class="table" style="background-color: #262626; color: white;">
        <thead style="position: sticky; top: 0;">
            <tr>
                <th style="width: 350px;">File Name</th>
                <th class="middle">DOWNLOAD </th>
                <th class="middle">DELETE</th>
            </tr>
        </thead>
        @foreach (FileModel file in Model)
        {
            <tr>
                <td>@file.FileName</td>
                <td style="vertical-align: middle; text-align: center;">
                    <button class="btn btn-success">
                        @Html.ActionLink("Download", "DownloadFile",
                         new { fileName = file.FileName })
                    </button>
                </td>
                <td style="vertical-align: middle; text-align: center;">
                    <button  class="btn btn-danger">
                        @Html.ActionLink("DELETE", "DeleteFile",
                       new { fileName = file.FileName },
                       new { onclick = "return confirm('Are you sure you wish to delete this?');" })
                    </button>
                </td>
            </tr>
        }
    </table>
</div>

u21447234_HW3/u21447234_HW3/Views/Home/AboutMe.cshtml
@{
    ViewBag.Title = "About Me";
    ViewBag.Message = "I'm Mitchell this is my About page, let's get started.";
}
<h2><b>@ViewBag.Title</b></h2>
<h4>@ViewBag.Message</h4>

<style>
    .responsive {
        width: 100%;
        max-width: 350px;
        height: auto;
        display: block;
        margin-left: auto;
        margin-right: auto;
    }

    body {
        background-image: linear-gradient(to left, white, lightblue, lightskyblue, dodgerblue);
        background-attachment: fixed;
    }
</style>

<div class="well-lg" style="background-color: #262626; color: white; ">
    <div class="row">
        <div class="col-xs-12 col-sm-6" style="text-align: center;">
            <h2 style="margin-top: -5px;"><b>Biography</b></h2>
            <p>My name is Mitchell Clark and once again I started coding my Homework task very close to the due date. I love coding and wish to one day beat my procrastination. During this project I made use of HTML, MVC, Bootstrap and razor.</p>
        </div>

        <div class="col-xs-12 col-sm-6" style="float: right;">
            <img src="https://www.w3schools.com/howto/img_avatar.png" class="responsive" alt="Photo">
        </div>
    </div>
</div>

u21447234_HW3/u21447234_HW3/Views/Home/Images.cshtml
@{
    ViewBag.Title = "Images";
}

<h2><b>@ViewBag.Title</b></h2>

u21447234_HW3/u21447234_HW3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    ViewBag.Message = "Please select an upload option and a file to upload.";
}
<h2><b>@ViewBag.Title</b></h2>
<h4>@ViewBag.Message</h4>

<style>
    body {
        background-image: linear-gradient(to right, white, lightblue, lightskyblue, dodgerblue);
        background-attachment: fixed;
    }
</style>

<div class="well-lg" style="background-color: #262626; color: white;">
    <div class="row">

        <div class="col-xs-12 col-lg-7" style="margin-top: -20px;">
            <h2>Description</h2>
            <p>This project focuses on file uploading and the displaying of said files. These files can be of a type Image, Video and Document. Each file type has its own view where you can delete or download said file.</p><br />
        </div>

        <div class="col-xs-12 col-lg-5">
            <form>
                <div class="row">
                    <div class="col-xs-12" style="margin-top: -20px;">
                        <div class="row">
                            <h2 style="margin-left: 15px;">Option Selection</h2>
                            @using (Html.BeginForm("Home", "Index", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                <div class="col-lg-4">
                                    <input type="radio" id="Doc" name="rbSelection" value="Doc">
                                    <label for="Doc">Document</label><br />

                                    <input type="radio" id="Img" name="rbSelection" value="Img">
                                    <label for="Img">Image</label><br />

                                    <input type="radio" id="Vid" name="rbSelection" value="Vid">
                                    <label for="Vid">Video</label><br />
                                </div>

                                <div class="col-lg-4">
                                    <input type="file" name="files" /><br />
                                    <input type="submit" class="btn btn-primary" value="Submit" />
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

u21447234_HW3/u21447234_HW3/Views/Home/Videos.cshtml
@{
    ViewBag.Title = "Videos";
}

<h2><b>@ViewBag.Title</b></h2>

u21447234_HW3/u21447234_HW3/Views/Image/Index.cshtml
@using u21447234_HW3.Models
@model List<FileModel>
    
@{
    ViewBag.Title = "Images";
    ViewBag.Message = "All your uploaded Images will appear here.";
}
<h2><b>@ViewBag.Title</b></h2>
<h4>@ViewBag.Message</h4>

<style>
    body {
        background-image: radial-gradient(circle, blue, aqua, lightskyblue, lightblue);
        background-attachment: fixed;
    }

    .card {
        height: 200px;
        margin-bottom: 10px;
        margin-top: 10px;
        position: relative;
        border: dashed;
        border-color: dimgrey;
    }

    .card-body {
        position: absolute;
        bottom: 2px;
        margin-left: 10px;
        margin-bottom: 10px;
    }
</style>

<div class="well-lg" style="background-color: #262626; color: white;">
    <div class="row">
        @foreach (FileModel images in Model)
        {
            <div class="col-lg-4">
                <div class="card">
                    <img src="~/App_Data/image/@images.FileName" alt="Card Image" />
                    <div class="card-body">
                        <h4>@images.FileName</h4>
                        <button class="btn btn-success">
                            @Html.ActionLink("Download", "DownloadImage",
                            new { fileName = images.FileName })
                        </button>
                        <button class="btn btn-danger">
                            @Html.ActionLink("DELETE", "DeleteImage",
                            new { fileName = images.FileName },
                            new { onclick = "return confirm('Are you sure you wish to delete this?');" })
                        </button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

u21447234_HW3/u21447234_HW3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HOME", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav ">
                    <li>@Html.ActionLink("Files", "Index", "File")</li>
                    <li>@Html.ActionLink("Images", "Index", "Image")</li>
                    <li>@Html.ActionLink("Videos", "Index", "Video")</li>
                    <li>@Html.ActionLink("About Me", "AboutMe", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; u21447234_HW3 Mitchell Clack</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

u21447234_HW3/u21447234_HW3/Views/Video/Index.cshtml
@using u21447234_HW3.Models
@model List<FileModel>

@{
    ViewBag.Title = "Videos";
    ViewBag.Message = "All your uploaded Videos will appear here.";
}

<h2><b>@ViewBag.Title</b></h2>
<h4>@ViewBag.Message</h4>

<style>
    body {
        background-image: radial-gradient(circle, blue, aqua, lightskyblue, lightblue);
        background-attachment: fixed;
    }

    .card {
        height: 200px;
        margin-bottom: 10px;
        margin-top: 10px;
        position: relative;
        border: dashed;
        border-color: dimgrey;
    }

    .card-body {
        position: absolute;
        bottom: 2px;
        margin-left: 10px;
        margin-bottom: 10px;
    }
</style>

<div class="well-lg" style="background-color: #262626; color: white;">
    <div class="row">
        @foreach (FileModel videos in Model)
        {
            <div class="col-lg-4">
                <div class="card">
                    <img src="~/App_Data/image/@videos.FileName" alt="Card Image" />
                    <div class="card-body">
                        <h4>@videos.FileName</h4>
                        <button class="btn btn-success">
                            @Html.ActionLink("Download", "DownloadVideos",
                            new { fileName = videos.FileName })
                        </button>
                        <button class="btn btn-danger">
                            @Html.ActionLink("DELETE", "DeleteVideos",
                            new { fileName = videos.FileName },
                            new { onclick = "return confirm('Are you sure you wish to delete this?');" })
                        </button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>